return {
  {
    "nvim-treesitter/nvim-treesitter",
    branch = "main",
    build = ":TSUpdate",
    lazy = false,
    opts = {
      ensure_installed = {
        "bash",
        "c",
        "comment",
        "cpp",
        "css",
        "csv",
        "diff",
        "dockerfile",
        "dot",
        "doxygen",
        "git_config",
        "git_rebase",
        "gitattributes",
        "gitcommit",
        "gitignore",
        "go",
        "gpg",
        "html",
        "htmldjango",
        "http",
        "ini",
        "javascript",
        "jq",
        "json",
        "json5",
        "linkerscript",
        "lua",
        "luadoc",
        "make",
        "markdown",
        "markdown_inline",
        "nix",
        "objdump",
        "passwd",
        "perl",
        "php",
        "phpdoc",
        "proto",
        "python",
        "query",
        "regex",
        "requirements",
        "rust",
        "sql",
        "ssh_config",
        "strace",
        "toml",
        "tsv",
        "udev",
        "verilog",
        "vim",
        "vimdoc",
        "xml",
        "yaml",
        "zig",
      },
      autotag = {
        enable = true,
      },
      endwise = {
        enable = true,
      },
      highlight = {
        enable = true,
      },
      indent = {
        enable = true,
      },
      matchup = {
        enable = true,
      },
    },
  },
  {
    "andymass/vim-matchup",
    init = function()
      vim.g.matchup_matchparen_deferred = 1
      vim.g.matchup_matchparen_hi_surround_always = 1
    end
  },
}
