return {
  "nvim-treesitter/nvim-treesitter",
  build = ":TSUpdate",
  config = function()
    local configs = require("nvim-treesitter.configs")
    configs.setup({
      ensure_installed = {
        "bash",
        "c",
        "comment",
        "cpp",
        "css",
        "csv",
        "diff",
        "dockerfile",
        "dot",
        "doxygen",
        "git_config",
        "git_rebase",
        "gitattributes",
        "gitcommit",
        "gitignore",
        "go",
        "gpg",
        "html",
        "htmldjango",
        "http",
        "ini",
        "javascript",
        "jq",
        "json",
        "json5",
        "linkerscript",
        "lua",
        "luadoc",
        "make",
        "markdown",
        "markdown_inline",
        "nix",
        "objdump",
        "passwd",
        "perl",
        "php",
        "phpdoc",
        "proto",
        "python",
        "query",
        "regex",
        "requirements",
        "rust",
        "sql",
        "ssh_config",
        "strace",
        "toml",
        "tsv",
        "udev",
        "verilog",
        "vim",
        "vimdoc",
        "xml",
        "yaml",
        "zig",
      },
      autotag = {
        enable = true,
      },
      endwise = {
        enable = true,
      },
      highlight = {
        enable = true,
      },
      indent = {
        enable = true,
      },
    })
  end,
}
